### ISSUE TITLE
`addParticipants` should accept `user.id` from skygear SDK directly

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#31]

**Comment by chankiyu22** [comment]
`addParticipants(conversation_id, participants_ids)` adds participants(skygear users) to a conversation by passing an array of user id to the second parameter.

It is unclear that the participant_ids column should store an array of user reference or user id such that it is valid to pass both `user.id` or `user._id` to it.

Maybe related to `after_save` or `before_save` event to create a new user_conversation record due to change of participants.

**Comment by rickmak** [comment]
Resolved at e00b3e8d
